############################################################
# Dockerfile
############################################################

# Set the base image
FROM centos:latest

# File Author / Maintainer
MAINTAINER cds

# Install Packages






RUN yum install -y epel-release
RUN yum install -y nginx







#create folders




#attache volumes



# Usage: ADD [source directory or URL] [destination directory]



#ports exposed



